// Mocks generated by Mockito 5.3.0 from annotations
// in xkcd_app/test/features/comics_feed/domain/usecases/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:xkcd_app/features/comics_feed/domain/entities/comics_feed_entity.dart'
    as _i6;
import 'package:xkcd_app/features/comics_feed/domain/repositories/comics_feed_repository.dart'
    as _i3;
import 'package:xkcd_app/core/error/failures.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [ComicsFeedRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockComicsFeedRepository extends _i1.Mock
    implements _i3.ComicsFeedRepository {
  MockComicsFeedRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ComicsFeedEntity>> getComic(int? id) =>
      (super.noSuchMethod(Invocation.method(#getComic, [id]),
          returnValue:
              _i4.Future<_i2.Either<_i5.Failure, _i6.ComicsFeedEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ComicsFeedEntity>(
                      this, Invocation.method(#getComic, [id])))) as _i4
          .Future<_i2.Either<_i5.Failure, _i6.ComicsFeedEntity>>);
}
